import json

translations = {
    "Home": "Nyumbani",
    "Properties": "Mali",
    "About": "Kuhusu",
    "Contact": "Wasiliana",
    "Dashboard": "Dashibodi",
    "Add Listing": "Weka Nyumba",
    "Admin": "Msimamizi",
    "Admin Panel": "Jopo la Usimamizi",
    "Become an Agent": "Kuwa Wakala",
    "My Bookings": "Uhifadhi Wangu",
    "Change Theme": "Badili Muonekano",
    "Logout": "Toka",
    "Log In": "Ingia",
    "Sign Up": "Jisajili",
    "Login": "Ingia",
    "Register": "Jisajili",
    "Quick Links": "Viungo Muhimu",
    "Contact Us": "Wasiliana Nasi",
    "Phone:": "Simu:",
    "Email:": "Barua Pepe:",
    "All rights reserved.": "Haki zote zimehifadhiwa.",
    "About NyumbaHub": "Kuhusu NyumbaHub",
    "Switch to English": "Switch to English",
    "Badili kwenda Kiswahili": "Badili kwenda Kiswahili",
    "Search": "Tafuta",
    "Price": "Bei",
    "Location": "Mahali",
    "Bedrooms": "Vyumba",
    "Bathrooms": "Bafu",
    "Submit": "Wasilisha",
    "Save": "Hifadhi",
    "Cancel": "Ghairi",
    "Edit": "Hariri",
    "Delete": "Futa",
    "View": "Angalia",
    "Manage Profile": "Dhibiti Wasifu",
    "Settings": "Mipangilio",
    "Profile": "Wasifu",
    "Password": "Nenosiri",
    "Email": "Barua Pepe",
    "Name": "Jina",
    "First Name": "Jina la Kwanza",
    "Last Name": "Jina la Mwisho",
    "Address": "Anwani",
    "City": "Jiji",
    "State": "Mkoa",
    "Zip": "Postikodi",
    "Country": "Nchi",
    "Status": "Hali",
    "Active": "Inatumika",
    "Inactive": "Haifanyi kazi",
    "Pending": "Inasubiri",
    "Approved": "Imeidhinishwa",
    "Rejected": "Imekataliwa",
    "User": "Mtumiaji",
    "Agent": "Wakala",
    "Role": "Jukumu",
    "Action": "Hatua",
    "Actions": "Hatua",
    "Create": "Tengeneza",
    "Update": "Sasisha",
    "Title": "Kichwa",
    "Description": "Maelezo",
    "Image": "Picha",
    "Images": "Picha",
    "Upload": "Pakia",
    "Download": "Pakua",
    "Yes": "Ndio",
    "No": "Hapana",
    "Back": "Rudi",
    "Next": "Inayofuata",
    "Previous": "Iliyopita",
    "Filter": "Chuja",
    "Reset": "Weka upya",
    "Close": "Funga",
    "Open": "Fungua",
    "Menu": "Menyu",
    "Welcome": "Karibu",
    "Welcome back": "Karibu tena",
    "Forgot Password?": "Umesahau Nenosiri?",
    "Remember Me": "Nikumbuke",
    "Don't have an account?": "Hauna akaunti?",
    "Already have an account?": "Tayari una akaunti?",
    "Send Password Reset Link": "Tuma Kiungo cha Kuweka Upya Nenosiri",
    "Confirm Password": "Thibitisha Nenosiri",
    "Reset Password": "Weka Upya Nenosiri",
    "Property Details": "Maelezo ya Mali",
    "Agent Details": "Maelezo ya Wakala",
    "Contact Agent": "Wasiliana na Wakala",
    "Book a Viewing": "Hifadhi Miadi ya Kutazama",
    "Message": "Ujumbe",
    "Send Message": "Tuma Ujumbe",
    "Success": "Mafanikio",
    "Error": "Kosa",
    "Warning": "Onyo",
    "Info": "Maelezo",
    "Are you sure?": "Una uhakika?",
    "This action cannot be undone.": "Hatua hii haiwezi kutenduliwa.",
    "Confirm": "Thibitisha",
    "Are you sure you want to delete this?": "Una uhakika unataka kufuta hii?",
    "No data available": "Hakuna data",
    "Loading...": "Inapakia...",
    "Search...": "Tafuta...",
    "Select...": "Chagua...",
    "All": "Yote",
    "None": "Hakuna",
    "Other": "Nyingine",
    "Male": "Mwanaume",
    "Female": "Mwanamke",
    "Date": "Tarehe",
    "Time": "Saa",
    "Month": "Mwezi",
    "Year": "Mwaka",
    "Day": "Siku",
    "Hour": "Saa",
    "Minute": "Dakika",
    "Second": "Sekunde",
    "Today": "Leo",
    "Yesterday": "Jana",
    "Tomorrow": "Kesho",
    "Now": "Sasa",
    "Never": "Kamwe",
    "Always": "Daima",
    "Sometimes": "Wakati mwingine",
    "Often": "Mara nyingi",
    "Rarely": "Mara chache",
    "Type": "Aina",
    "Category": "Kundi",
    "Size": "Ukubwa",
    "Area": "Eneo",
    "Price": "Bei",
    "Currency": "Sarafu",
    "Language": "Lugha",
    "English": "Kiingereza",
    "Swahili": "Kiswahili",
    "Theme": "Muonekano",
    "Light": "Mwanga",
    "Dark": "Giza",
    "System": "Mfumo",
    "Appearance": "Muonekano",
    "Security": "Usalama",
    "Privacy": "Faragha",
    "Terms of Service": "Masharti ya Huduma",
    "Privacy Policy": "Sera ya Faragha",
    "Help": "Msaada",
    "FAQ": "Maswali Yanayoulizwa Mara kwa Mara",
    "Support": "Msaada",
    "Documentation": "Nyaraka",
    "API": "API",
    "Version": "Toleo",
    "Powered by": "Inawezeshwa na",
    "NyumbaHub": "NyumbaHub",
    "All Listings": "Nyumba Zote",
    "My Activity": "Shughuli Zangu",
    "Bookings": "Orodha za Kuhifadhi",
    "Career": "Kazi",
    "Sign Out": "Toka",
    "Manage Listings": "Dhibiti Nyumba",
    "My Listings": "Nyumba Zangu",
    "Add New Listing": "Weka Nyumba Mpya",
    "Main": "Kuu",
    "Browse Listings": "Vinjari Nyumba",
    "Manage Users": "Dhibiti Watumiaji",
    "User Management": "Usimamizi wa Watumiaji",
    "Agent Applications": "Maombi ya Wakala",
    "Properties": "Mali",
    "View Details": "Angalia Maelezo",
    "Read More": "Soma Zaidi"
}

with open('lang/sw.json', 'r') as f:
    sw_json = json.load(f)

updated_count = 0
for en, sw in translations.items():
    if en in sw_json:
        sw_json[en] = sw
        updated_count += 1
    # also add it even if it wasn't extracted (for controllers)
    else:
        sw_json[en] = sw
        updated_count += 1

with open('lang/sw.json', 'w') as f:
    json.dump(sw_json, f, indent=4)

print(f"Updated {updated_count} translations in sw.json")
